apiVersion: v1
kind: Service
metadata:
  name: devops-test-service
spec:
  selector:
    app: devops-test
  ports:
    - protocol: TCP
      port: 31001
      nodePort: 31001
      targetPort: devops-port
  type: NodePort
