apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
  - name: http
    port: 80
    targetPort: wordpress-port
  - name: https
    port: 443
    targetPort: wordpress-port
    protocol: TCP
## I have configured the wordpress runs in AWS Load Balancer, If you would like to execute it in Minikube please change the type: NodePort
  type: LoadBalancer
