apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx        
  ports:
    - protocol: TCP
      port: 31002
      nodePort: 31002
      targetPort: nginx-port
  type: NodePort
